### ISSUE TITLE
cannot parse simple date

### ISSUE THREAD

**Issue by davidem00** [mattkrins/CalendarAdd#1]
tool only creates an event for "today"

**Comment by mattkrins** [comment]
It was not designed to do this, but if you would like to request this as a feature i can implement it.

**Comment by mattkrins** [comment]
Feature added to version 1.2
https://github.com/mattkrins/CalendarAdd/commit/df2b4ce940717d3819ec6f89407dc82901c48e75

**Comment by davidem00** [comment]
I see.  There was a prior collection of tools which did this (parsing the selection for Title, Date, and detail, and they are (both) now broken.  It just seems to be a natural feature for such a tool so that it does something more than just copy & pasting into the details (plus the URL).

**Comment by mattkrins** [comment]
That simplicity is the entire point of this extension. I don't want complex functions that can break.
